baseURL = 'https://acmer.info'
languageCode = 'zh-cn'
title = 'ACMer.info'
DefaultContentLanguage = "zh-cn"
theme = "hugo-theme-codex"
copyright = "Licensed under CC BY-NC-SA 4.0 | © {year} ACMer.info and All Contributors"
disableKinds = ["sitemap", "RSS", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

# Optional params
[params]
  # Follow the Hugo date/time format reference here: 
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "Jan 2 2006"

  # Links to your social accounts, comment/uncomment as needed. Icons will be displayed for those specified.
  # twitter = "https://twitter.com/<your handle>"
  # github = "https://github.com/<your handle>"
  # email = "mailto:<your email>"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  # gitlab = "https://gitlab.com/<your handle>"
  # instagram = "https://instagram.com/<your handle>"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  
  # Titles for your icons (shown as tooltips), and also their display order.
  # Currently, these icons are supported: 
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube"
  # iconOrder = ["Twitter", "GitHub"]

  # Metadata for Twitter cards, defaults to params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

# Controls the navigation
[[menu.main]]
  identifier = "about"
  name = "关于"
  title = "关于"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "groups"
  name = "群组"
  title = "群组"
  url = "/groups"
  weight = 2

[[menu.main]]
  identifier = "ojs"
  name = "测评系统"
  title = "测评系统"
  url = "/ojs"
  weight = 3

[[menu.main]]
  identifier = "blogs"
  name = "选手博客"
  title = "选手博客"
  url = "/blogs"
  weight = 4

[[menu.main]]
  identifier = "studyMaterials"
  name = "学习资料"
  title = "学习资料"
  url = "/studyMaterials"
  weight = 5

[[menu.main]]
  identifier = "contest"
  name = "最近赛事"
  title = "最近赛事"
  url = "/contest"
  weight = 6

[[menu.main]]
  identifier = "interviews"
  name = "选手访谈"
  title = "选手访谈"
  url = "/interviews"
  weight = 6
